### ISSUE TITLE
Failed to retrieve the ms-Mcs-AdmPwd

### ISSUE THREAD

**Issue by aksharbarot** [jborean93/ansible-role-win_laps#1]
Hi,

laps_password lookup is giving error *"An unhandled exception occurred while running the lookup plugin 'laps_password'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Failed to retrieve the ms-Mcs-AdmPwd attribute for MACHINE01"*

-------Playbook-------------
 - name: get the LAPS managed password for a host
       debug:
         msg: "{{ lookup('laps_password', 'MACHINE01', domain_server='dc01.example.com', username='test@DC01.EXAMPLE.COM', password='test@123', search_base='OU=Test,OU=Workstation,OU=Testing,OU=Computers,OU=Objects,DC=dc01,DC=example,DC=com') }}"

**Comment by jborean93** [comment]
While this plugin is really only designed as a test one, the user must have the correct permissions on the object to be able to retrieve the password. Have a read through the section `Permission to read the password from AD` at https://blogs.msdn.microsoft.com/laps/2015/06/01/laps-and-password-storage-in-clear-text-in-ad/.

**Comment by jborean93** [comment]
As well as this, all traffic sent sent and received by that plugin is in plaintext. It should not be used in a production environment unless it is configured over LDAPS instead of just LDAP.

**Comment by jborean93** [comment]
I also recommend you look at https://github.com/ansible/ansible/pull/52012  which is a PR that implements more of the secure LDAP features that protect the credentials going over the network. I'm hoping to have that included in the Ansible 2.8 release bu there are no guarantees there.

**Comment by jborean93** [comment]
https://github.com/ansible/ansible/pull/52012 has been merged, please use that instead of this testing version.
